/* eslint-disable no-redeclare */
// source https://github.com/aikoven/typescript-fsa-redux-saga/blob/master/src/index.ts
// remove the throw error code from source

import { AxiosPromise, AxiosResponse } from 'axios'
import { SagaIterator } from 'redux-saga'
import { call, cancelled, fork, put, takeEvery } from 'redux-saga/effects'
import { Action, ActionCreator, AsyncActionCreators } from 'typescript-fsa'

export function bindAsyncAction<R>(
  actionCreators: AsyncActionCreators<void, R, any>
): {
  (worker: () => Promise<R> | SagaIterator): () => SagaIterator

  (worker: (params: void) => Promise<R> | SagaIterator): (params: void) => SagaIterator

  <A1>(worker: (params: void, arg1: A1) => Promise<R> | SagaIterator): (
    params: void,
    arg1: A1
  ) => SagaIterator

  <A1, A2>(worker: (params: void, arg1: A1, arg2: A2) => Promise<R> | SagaIterator): (
    params: void,
    arg1: A1,
    arg2: A2
  ) => SagaIterator

  <A1, A2, A3>(
    worker: (
      params: void,
      arg1: A1,
      arg2: A2,
      arg3: A3,
      ...rest: any[]
    ) => Promise<R> | SagaIterator
  ): (params: void, arg1: A1, arg2: A2, arg3: A3, ...rest: any[]) => SagaIterator
}
export function bindAsyncAction<P, R>(
  actionCreators: AsyncActionCreators<P, R, any>
): {
  (worker: (params: P) => Promise<R> | SagaIterator): (params: P) => SagaIterator

  <A1>(worker: (params: P, arg1: A1) => Promise<R> | SagaIterator): (
    params: P,
    arg1: A1
  ) => SagaIterator

  <A1, A2>(worker: (params: P, arg1: A1, arg2: A2) => Promise<R> | SagaIterator): (
    params: P,
    arg1: A1,
    arg2: A2
  ) => SagaIterator

  <A1, A2, A3>(
    worker: (params: P, arg1: A1, arg2: A2, arg3: A3, ...rest: any[]) => Promise<R> | SagaIterator
  ): (params: P, arg1: A1, arg2: A2, arg3: A3, ...rest: any[]) => SagaIterator
}

export function bindAsyncAction(actionCreator: AsyncActionCreators<any, any, any>) {
  return (worker: (params: any, ...args: any[]) => Promise<any> | SagaIterator) => {
    function* boundAsyncActionSaga(params: any, ...args: any[]): SagaIterator {
      yield put(actionCreator.started(params))

      try {
        const result = yield (call as any)(worker, params, ...args)
        yield put(actionCreator.done({ params, result }))
        return result
      } catch (error) {
        yield put(actionCreator.failed({ params, error }))
        // throw error
      } finally {
        if (yield cancelled()) {
          yield put(actionCreator.failed({ params, error: 'cancelled' }))
        }
      }
    }

    const capName = worker.name.charAt(0).toUpperCase() + worker.name.substring(1)

    return setFunctionName(boundAsyncActionSaga, `bound${capName}(${actionCreator.type})`)
  }
}

/**
 * Set function name.
 *
 * Note that this won't have effect on built-in Chrome stack traces, although
 * useful for stack traces generated by `redux-saga`.
 */
function setFunctionName<F extends Function>(func: F, name: string): F {
  try {
    Object.defineProperty(func, 'name', {
      value: name,
      configurable: true,
    })
  } catch (e) {
    // ignore
  }

  return func
}

/**
 * 本函数根据一个action来触发异步action，调用异步操作，自动获取返回值
 * @param action 触发action
 * @param asyncAction 异步action
 * @param asyncCall 异步调用，一般为api调用，调用成功触发异步action的success回调，payload包含异步调用成功的返回值
 */
export function takeAsyncAction<S, E>(
  action: ActionCreator<any>,
  asyncAction: AsyncActionCreators<any, S, E>,
  asyncCall: () => AxiosPromise<S>
): any

export function takeAsyncAction<P, S, E>(
  action: ActionCreator<P>,
  asyncAction: AsyncActionCreators<P, S, E>,
  asyncCall: (p: P) => AxiosPromise<S>
): any

export function takeAsyncAction<P, S, E>(
  action: ActionCreator<P>,
  asyncAction: AsyncActionCreators<P, S, E>,
  asyncCall: (p: P) => AxiosPromise<S>
) {
  const worker = bindAsyncAction(asyncAction)(function* (params): SagaIterator {
    const res: AxiosResponse<S> = yield call(asyncCall, params)
    return res.data
  })

  function* saga(sagaAction: Action<P>): SagaIterator {
    yield fork(worker, sagaAction.payload)
  }

  return takeEvery(action, saga)
}
